Repository Automattic/simplenote-macos, pull requests merged in 2019-05, with the labels that each got.

#313 Update Tracks to send `userID` Field.
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/SPAutomatticTracker.m
Labels: analytics

#306 Update Tracks to the most recent version
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
Labels: analytics

#319 Update GitHub Templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#320 Issue/ignore config.plist
  CONTRIBUTING.md
  Simplenote/config-demo.plist
  readme.md
Labels: task

#323 Added build tooling + XCode 10.2/Swift 5 updates
  .bundle/config
  .gitignore
  External/Notepad/Storage.swift
  External/Notepad/Style.swift
  External/Notepad/Theme.swift
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  Rakefile
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSString+Escaping.m
  Simplenote/SimplenoteAppDelegate.m
  readme.md
Labels: task, tooling

#324 Add secret store
  .configure
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#329 Updated Simperium lib from 0.8.19 to 0.8.21
  Podfile
  Podfile.lock
Labels: debt, task

#302 Add the unicode bullet • to the list of bullets
  Simplenote/NSTextView+Simplenote.m
Labels: enhancement

#333 Editor: History Versions is now capped to 30
  Simplenote/NoteEditorViewController.m
Labels: enhancement

#332 Cleanup
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/ 
Labels: debt

#335 Add CircleCI config
  .circleci/config.yml
  .gitignore
  Simplenote.xcworkspace/contents.xcworkspacedata
  Simplenote.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: tooling

#336 Add configuration for Hound and Swiftlint
  .hound.yml
  .swiftlint.yml
Labels: tooling
