Repository Automattic/simplenote-macos, pull requests merged in 2019-11, with the labels that each got.

#394 Fixing crash at Launch
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController.m
  Simplenote/SimplenoteAppDelegate.m
Labels: bug

#396 Fixing Emoji's AWOL Bug
  External/Notepad/Storage.swift
  RELEASE-NOTES.txt
  Simplenote/NoteEditorViewController.m
  Simplenote/SPTextView.m
Labels: bug

#398 Fixing Emojis Crash
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: bug, crash

#399 Merge Release/1.8 into develop
  RELEASE-NOTES.txt
  config/Version.public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#403 Fixing Checklist Asset
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked.png
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked@2x.png
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked@3x.png
Labels: bug

#404 Fixing Checklist Asset
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked.png
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked@2x.png
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked@3x.png
Labels: bug
