Repository Automattic/simplenote-macos, pull requests merged in 2019-12, with the labels that each got.

#412 Merge release/1.9 into develop
  config/Version.public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#411 Merge Release/1.8 into develop
  .circleci/config.yml
  .gitignore
  External/Notepad/Storage.swift
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/CrashLogging.swift
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked.png
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked@2x.png
  Simplenote/Images.xcassets/icon_task_checked.imageset/task_checked@3x.png
  Simplenote/LoginWindowController.m
  Simplenote/NoteEditorViewController.m
  Simplenote/SPCredentials-demo.swift
  Simplenote/SPTextView.m
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/config-demo.plist
  config/Version.public.xcconfig
  fastlane/Deliverfile
  readme.md
Labels: Releases

#408 Add beta build lane
  .gitignore
  .ruby-version
  Gemfile
  Gemfile.lock
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/env.example
Labels: tooling

#415 Update XCode version on CI
  .circleci/config.yml
Labels: tooling

#421 Fix: Surrogate Pairs (Mark II)
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [priority] high

#423 Updates Simperium to Mark 0.8.26
  Podfile
  Podfile.lock
Labels: [priority] high

#426 Merge release 1.8.1 into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Releases

#425 Merge Release/1.8.1 into Master
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  config/Version.public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#435 Restoring Trash Menu
  RELEASE-NOTES.txt
  Simplenote/SPTableView.h
  Simplenote/SPTableView.m
  Simplenote/SPTagCellView.h
  Simplenote/SPTagCellView.m
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/en.lproj/MainMenu.xib
Labels: bug
