Repository Automattic/simplenote-macos, pull requests merged in 2019-07, with the labels that each got.

#346 Merge Release/1.5.0 into Master
  .bundle/config
  .circleci/config.yml
  .configure
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .hound.yml
  .swiftlint.yml
  CONTRIBUTING.md
  External/Notepad/Storage.swift
  External/Notepad/Style.swift
  External/Notepad/Theme.swift
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Rakefile
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote-AppStore.xcscheme
  Simplenote.xcworkspace/contents.xcworkspacedata
  Simplenote.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Simplenote/ 
  Simplenote/AboutViewController.swift
  Simplenote/CrashLogging.swift
  Simplenote/NSString+Escaping.m
  Simplenote/NSTextView+Simplenote.m
  Simplenote/NoteEditorViewController.m
  Simplenote/Preferences.m
  Simplenote/SPAutomatticTracker.m
  Simplenote/SPMarkdownParser.m
  Simplenote/SPTextView.m
  Simplenote/SPWindow.m
  Simplenote/Simplenote-DB5.plist
  Simplenote/Simplenote-Info-Hockey.plist
  Simplenote/Simplenote-Info.plist
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/config-demo.plist
  Simplenote/en.lproj/MainMenu.xib
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  readme.md
Labels: Releases

#348 Reduce number of conflicts in RELEASE-NOTES.txt
  .gitattributes
Labels: tooling

#347 Published Icon
  RELEASE-NOTES.txt
  Simplenote.xcworkspace/contents.xcworkspacedata
  Simplenote/Images.xcassets/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/icon_shared.imageset/icon_shared@1x.png
  Simplenote/Images.xcassets/icon_shared.imageset/icon_shared@2x.png
  Simplenote/NSImage+Colorize.h
  Simplenote/NSImage+Colorize.m
  Simplenote/NoteListViewController.m
  Simplenote/SPNoteCellView.h
  Simplenote/SPNoteCellView.m
  Simplenote/SPTextAttachment.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: enhancement

#350 Update the project to use external xcconfig file for versioning
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Simplenote-Info-Hockey.plist
  Simplenote/Simplenote-Info.plist
  config/Simplenote.debug.xcconfig
  config/Simplenote.release.xcconfig
  config/Version.public.xcconfig
Labels: tooling

#351 Add codefreeze automation
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Releases

#354 Fix incorrect crash log environment detection
  Simplenote/CrashLogging.swift
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
Labels: bug

#356 Notes Exporter
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSObject+Helpers.swift
  Simplenote/SPExporter.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/en.lproj/MainMenu.xib
Labels: enhancement

#358 Update fastlane
  Gemfile
  Gemfile.lock
Labels: tooling
