Repository Automattic/simplenote-macos, pull requests merged in 2019-08, with the labels that each got.

#364 Merge Release/1.6 into develop
  config/Version.public.xcconfig
Labels: Releases

#370 1 Infinite Loop Bugfix
  External/custom-scroller/MMScrollView.m
Labels: [priority] high

#374 About: Nukes Simperium Link
  Simplenote/About.storyboard
  Simplenote/AboutViewController.swift
Labels: [feature] settings

#375 Updates SignUp password length
  Simplenote/LoginWindowController.m
Labels: [feature] login

#377 Update release-toolkit to 0.7.1
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#378 Privacy Policy: Enhanced UI
  Simplenote/Privacy.storyboard
  Simplenote/PrivacyViewController.swift
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
Labels: [priority] high

#379 Nü Credentials Mechanism
  .circleci/config.yml
  .gitignore
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/CrashLogging.swift
  Simplenote/LoginWindowController.m
  Simplenote/SPCredentials-demo.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/config-demo.plist
  readme.md
Labels: debt
