Repository Automattic/simplenote-macos, pull requests merged in 2020-09, with the labels that each got.

#662 Merge release 2.1 beta 1 into develop
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.public.xcconfig
Labels: Releases

#660 Simplenote goes Storyboard
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/Main.storyboard
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSStoryboard+Simplenote.swift
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.m
  Simplenote/Options.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.m
  Simplenote/en.lproj/MainMenu.strings
Labels: debt

#671 Linkifying on Paste ©
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/SPTableView.h
  Simplenote/SPTableView.m
  Simplenote/SPTextView.h
  Simplenote/SPTextView.m
Labels: interlinking

#672 Switch configuration to trunk
  .configure
  Gemfile.lock
Labels: tooling

#673 Markdown: Dark Mode Highlight
  RELEASE-NOTES.txt
  Simplenote/CSS/markdown-dark.css
Labels: [feature] markdown

#667 Editor: Copy Interlink Action
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/NSPasteboard+Simplenote.swift
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/Note+Interlinks.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
  Simplenote/SimplenoteConstants.swift
  Simplenote/String+Simplenote.swift
  SimplenoteTests/StringSimplenoteTests.swift
Labels: interlinking

#668 List: New Actions!
  RELEASE-NOTES.txt
  Simplenote/Main.storyboard
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
Labels: interlinking

#670 Interlinks: Navigation Support
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/MarkdownViewController.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SPTableView.h
  Simplenote/SPTableView.m
  Simplenote/SPTextView.h
  Simplenote/SPTextView.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListState.swift
  Simplenote/TagListViewController.m
  Simplenote/URL+Interlink.swift
Labels: interlinking

#675 Merge release 2.1 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
Labels: Releases

#677 Merge 2.2 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases
