Repository Automattic/simplenote-macos, pull requests merged in 2020-10, with the labels that each got.

#674 Interlinks: Autocomplete Tooling
  .circleci/config.yml
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: interlinking

#681 LoginWindowController: Resetting Frame Origin
  RELEASE-NOTES.txt
  Simplenote/LoginWindowController.m
Labels: bug

#678 Interlinks Autocomplete UI: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Interlink.storyboard
  Simplenote/InterlinkViewController.swift
  Simplenote/InterlinkWindowController.swift
  Simplenote/LinkTableCellView.swift
  Simplenote/NSStoryboard+Simplenote.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
Labels: interlinking

#682 Interlinks Autocomplete UI: Mark III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Interlink.storyboard
  Simplenote/InterlinkViewController.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/SPTableView.h
  Simplenote/SPTableView.m
Labels: interlinking

#680 Interlinks Autocomplete UI: Mark II
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AutocompleteWindow.swift
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/Interlink.storyboard
  Simplenote/InterlinkViewController.swift
  Simplenote/InterlinkWindowController.swift
  Simplenote/NSEvent+Simplenote.swift
  Simplenote/NSTableView+Simplenote.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/SPWindow.h
  Simplenote/SPWindow.m
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/Window.swift
Labels: interlinking

#685 Merge release 2.2 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#688 Interlinks Autocomplete UI: Mark III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Interlink.storyboard
  Simplenote/InterlinkViewController.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/SPTableView.h
  Simplenote/SPTableView.m
Labels: interlinking

#689 Interlinks Autocomplete UI: Mark IV
  Simplenote/InterlinkViewController.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
Labels: interlinking

#690 Interlinks Autocomplete UI: Key Exclusions
  Simplenote/AutocompleteWindow.swift
Labels: interlinking

#692 Interlink: Fixing Undo + Preventing Recursive Links
  Simplenote/InterlinkViewController.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
Labels: interlinking

#684 About: Adds Get Help row
  RELEASE-NOTES.txt
  Simplenote/About.storyboard
  Simplenote/AboutViewController.swift
  Simplenote/BackgroundView.swift
Labels: enhancement

#697 Merge release 2.3 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#696 Interlink References
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/HeaderTableCellView.swift
  Simplenote/InterlinkViewController.swift
  Simplenote/MetricTableViewCell.swift
  Simplenote/MetricsViewController.swift
  Simplenote/MetricsViewController.xib
  Simplenote/NSPasteboard+Simplenote.swift
  Simplenote/Note+Interlinks.swift
  Simplenote/NoteMetrics.swift
  Simplenote/NumberFormatter+Simplenote.swift
  Simplenote/ReferenceTableViewCell.swift
  Simplenote/SeparatorTableViewCell.swift
  Simplenote/TagListViewController+Swift.swift
Labels: interlinking

#699 Interlink References: Mark II
  RELEASE-NOTES.txt
  Simplenote/MetricsViewController.swift
  Simplenote/MetricsViewController.xib
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/ReferenceTableViewCell.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/TagListRow.swift
Labels: interlinking

#701 CONTRIBUTING.md: Add information about our PR merge policy
  CONTRIBUTING.md
Labels: documentation
