Repository Automattic/simplenote-macos, pull requests merged in 2020-06, with the labels that each got.

#550 Stronger Passwords 🔥
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote/LoginWindowController.m
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  Simplenote/SimplenoteAppDelegate.m
Labels: [feature] security

#549 Refreshing Tags Editor: Mark 1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Array+Simplenote.swift
  Simplenote/BackgroundView.swift
  Simplenote/NSAttributedString+Simplenote.swift
  Simplenote/Note+Simplenote.swift
  Simplenote/Note.m
  Simplenote/NoteEditorBottomBar.h
  Simplenote/NoteEditorBottomBar.m
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.h
  Simplenote/SPGradientView.h
  Simplenote/SPGradientView.m
  Simplenote/SPTokenField.h
  Simplenote/SPTokenField.m
  Simplenote/Simperium+Simplenote.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagsField.swift
  Simplenote/en.lproj/MainMenu.xib
  SimplenoteTests/NSAttributedStringSimplenoteTests.swift
Labels: spring cleaning

#556 Editor: Adjusting Metrics
  External/Notepad/Theme.swift
  RELEASE-NOTES.txt
  Simplenote/NoteEditorViewController.h
Labels: spring cleaning

#557 Merge 1.11.0-beta1 into develop
  config/Version.public.xcconfig
Labels: Releases

#551 Refreshing Tags Editor: Mark 2
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/BackgroundView.swift
  Simplenote/NSAttributedString+Simplenote.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/TagAttachmentCell.swift
  Simplenote/TagsField.swift
  Simplenote/TagsFieldCell.swift
  Simplenote/UnicodeScalar+Simplenote.swift
  Simplenote/en.lproj/MainMenu.xib
  SimplenoteTests/NSAttributedStringSimplenoteTests.swift
Labels: spring cleaning

#561 Disables TabBar Support
  Simplenote/en.lproj/MainMenu.xib
Labels: bug

#558 Refreshing Tags Editor: Mark 3
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Array+Simplenote.swift
  Simplenote/HorizontalScrollView.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/TagsField.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: [feature] tags, spring cleaning

#565 Untagged Notes Filter: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSPredicate+Simplenote.swift
  Simplenote/NoteListViewController.m
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.m
  SimplenoteTests/NSPredicateSimplenoteTests.swift
Labels: spring cleaning

#574 Encryption Flag
  Simplenote/Simplenote-Info-Hockey.plist
  Simplenote/Simplenote-Info.plist
Labels: enhancement

#572 Merge release 1.11 into develop
  Simplenote/en.lproj/MainMenu.xib
  config/Version.public.xcconfig
Labels: Releases

#566 Untagged Notes Filter: Mark II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.m
  Simplenote/SPTableView.h
  Simplenote/SPTableView.m
  Simplenote/TagListRow.swift
  Simplenote/TagListState.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
Labels: spring cleaning

#569 Untagged Notes Filter: Mark III
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Images.xcassets/Buttons/button_untagged.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_untagged.imageset/icon_untagged.pdf
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SpacerTableViewCell.swift
  Simplenote/TagListRow.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#571 New Metrics Screen: Mark 0
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Images.xcassets/Buttons/button_ellipsis.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_ellipsis.imageset/button_ellipsis.pdf
  Simplenote/NSAppearance+Simplenote.swift
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NSVisualEffectView+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/TagListViewController.m
Labels: spring cleaning

#576 Privacy Notice for California Users
  RELEASE-NOTES.txt
  Simplenote/About.storyboard
  Simplenote/AboutViewController.swift
Labels: [priority] high
