Repository Automattic/simplenote-macos, pull requests merged in 2020-08, with the labels that each got.

#612 Fastlane: Finalize Release
  RELEASE-NOTES.txt
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: i18n, tooling

#623 TagListState: rowAtIndex bounds check
  RELEASE-NOTES.txt
  Simplenote/TagListState.swift
  Simplenote/TagListViewController+Swift.swift
Labels: crash

#630 Bugfix: All Notes AWOL
  Simplenote/TagListState.swift
Labels: bug

#628 Burning Dead Code 🔥
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSObject+Simplenote.h
  Simplenote/NSObject+Simplenote.m
  Simplenote/NSString+Metadata.h
  Simplenote/NSString+Metadata.m
  Simplenote/NSString+Simplenote.h
  Simplenote/NSString+Simplenote.m
  Simplenote/NSView+Simplenote.h
  Simplenote/NSView+Simplenote.m
  Simplenote/Note.h
  Simplenote/Note.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Tag.h
  Simplenote/Tag.m
Labels: debt

#631 NoteEditorViewController: Nullability Specifiers
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
Labels: debt

#641 Add a testing checklist
  TESTING-CHECKLIST.md
Labels: documentation, enhancement

#638 Merge 2.0.0 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
Labels: Releases

#632 Editor: Decoupling from Notes List
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/NSSearchField+Simplenote.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
Labels: debt

#633 Notes List Cleanup
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/Options.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: debt

#634 Notes List: Dropping NSMenu Outlets
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/Options.swift
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
Labels: debt

#645 Fix: Unresponsive Tags List
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/ClipView.swift
  Simplenote/SPTableView.h
  Simplenote/SPTableView.m
Labels: bug

#648 Adds Missing Localization
  Simplenote/Privacy.storyboard
  Simplenote/PrivacyViewController.swift
Labels: bug, i18n

#649 Fixing Main Window Autosave mechanism
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSWindowFrameAutosaveName+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
Labels: bug

#650 Use the `main` mobile secrets branch
  .configure
Labels: accessibility

#646 Refreshing Markdown Preview onChange
  RELEASE-NOTES.txt
  Simplenote/MarkdownViewController.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
Labels: bug

#652 Integrates Simplenote Foundation
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/EntityObserver.swift
  Simplenote/MetricsViewController.swift
  Simplenote/PublishViewController.swift
Labels: [feature] search

#651 Integrates Simplenote Search
  .circleci/config.yml
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/EntityObserver.swift
  Simplenote/MarkdownViewController.swift
  Simplenote/MetricsViewController.swift
  Simplenote/NSPredicate+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/PublishViewController.swift
  Simplenote/SPBucket+Simplenote.swift
  Simplenote/Simperium+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  SimplenoteTests/NSPredicateSimplenoteTests.swift
Labels: [feature] search

#655 Merge release 2.0 into develop
  Simplenote/Simplenote-Info-Hockey.plist
  Simplenote/Simplenote-Info.plist
  config/Version.public.xcconfig
Labels: Releases

#659 Authentication: Displaying Titlebar's Close Button
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/SimplenoteAppDelegate.m
Labels: [priority] high

#654 Drops NSMenu ivar
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/Options.swift
  Simplenote/SPMarkdownParser.m
  Simplenote/SPTextView.h
  Simplenote/SPTextView.m
  Simplenote/UserDefaults+Simplenote.swift
Labels: debt
