Repository Automattic/simplenote-macos, pull requests merged in 2020-04, with the labels that each got.

#475 Lists: Undo Exceptions Mark V
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/SPTextView.m
  Simplenote/TextViewInputHandler.swift
  SimplenoteTests/NSTextViewSimplenoteTests.swift
  SimplenoteTests/TextViewInputHandlerTests.swift
Labels: bug, debt

#480 Merge release/1.10 into develop
  config/Version.public.xcconfig
Labels: Releases

#489 Decoupling VersionsViewController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/VersionsViewController.h
  Simplenote/VersionsViewController.m
  Simplenote/VersionsViewController.swift
  Simplenote/VersionsViewController.xib
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#491 Decoupling ShareViewController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/ShareViewController.h
  Simplenote/ShareViewController.m
  Simplenote/ShareViewController.swift
  Simplenote/ShareViewController.xib
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#483 Move env example file to new default location
  fastlane/Fastfile
  fastlane/env/user.env-example
Labels: tooling

#492 Decoupling PublishViewController
  DB5/VSTheme.h
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/PublishViewController.h
  Simplenote/PublishViewController.m
  Simplenote/PublishViewController.swift
  Simplenote/PublishViewController.xib
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#479 Color Studio: Mark 1
  DB5/VSThemeManager.m
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AppKitConstants.swift
  Simplenote/ColorStudio.swift
  Simplenote/NSAppearance+Simplenote.swift
  Simplenote/NSColor+Simplenote.h
  Simplenote/NSColor+Simplenote.m
  Simplenote/NSColor+Simplenote.swift
  Simplenote/NSColor+Studio.swift
  Simplenote/SPBackgroundView.m
  Simplenote/SPMarkdownParser.m
  Simplenote/SPTableRowView.m
  Simplenote/SPToolbarView.m
  Simplenote/SPUserInterface.swift
Labels: debt, spring cleaning

#493 Unlinking ViewController(s)
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#506 Drops unused assets
  Simplenote/Images.xcassets/button_delete.imageset/Contents.json
  Simplenote/Images.xcassets/button_delete.imageset/button_delete.png
  Simplenote/Images.xcassets/button_delete.imageset/button_delete@2x.png
  Simplenote/Images.xcassets/button_fullscreen.imageset/Contents.json
  Simplenote/Images.xcassets/button_fullscreen.imageset/button_fullscreen.png
  Simplenote/Images.xcassets/button_fullscreen.imageset/button_fullscreen@2x.png
  Simplenote/Images.xcassets/button_info.imageset/Contents.json
  Simplenote/Images.xcassets/button_info.imageset/button_info.png
  Simplenote/Images.xcassets/button_info.imageset/button_info@2x.png
  Simplenote/Images.xcassets/button_sidebar_hide.imageset/Contents.json
  Simplenote/Images.xcassets/button_sidebar_hide.imageset/button_sidebar_hide.png
  Simplenote/Images.xcassets/button_sidebar_hide.imageset/button_sidebar_hide@2x.png
  Simplenote/Images.xcassets/button_sidebar_hide_dark.imageset/Contents.json
  Simplenote/Images.xcassets/button_sidebar_hide_dark.imageset/button_sidebar_hide_dark.png
  Simplenote/Images.xcassets/button_sidebar_hide_dark.imageset/button_sidebar_hide_dark@2x.png
  Simplenote/Images.xcassets/button_sidebar_show.imageset/Contents.json
  Simplenote/Images.xcassets/button_sidebar_show.imageset/button_sidebar_show.png
  Simplenote/Images.xcassets/button_sidebar_show.imageset/button_sidebar_show@2x.png
  Simplenote/Images.xcassets/button_sidebar_show_dark.imageset/Contents.json
  Simplenote/Images.xcassets/button_sidebar_show_dark.imageset/button_sidebar_show_dark.png
  Simplenote/Images.xcassets/button_sidebar_show_dark.imageset/button_sidebar_show_dark@2x.png
  Simplenote/Images.xcassets/button_versions.imageset/Contents.json
  Simplenote/Images.xcassets/button_versions.imageset/button_versions.png
  Simplenote/Images.xcassets/button_versions.imageset/button_versions@2x.png
  Simplenote/Images.xcassets/focus_mode.imageset/Contents.json
  Simplenote/Images.xcassets/focus_mode.imageset/focus_mode.png
  Simplenote/Images.xcassets/focus_mode.imageset/focus_mode@2x.png
  Simplenote/Images.xcassets/focus_mode.imageset/focus_mode@3x.png
  Simplenote/Images.xcassets/icon_tag.imageset/Contents.json
  Simplenote/Images.xcassets/icon_tag.imageset/icon_tag.png
  Simplenote/Images.xcassets/icon_tag.imageset/icon_tag@2x.png
  Simplenote/Images.xcassets/icon_tag_grey.imageset/Contents.json
  Simplenote/Images.xcassets/icon_tag_grey.imageset/icon_tag_grey.png
  Simplenote/Images.xcassets/icon_tag_grey.imageset/icon_tag_grey@2x.png
  Simplenote/Images.xcassets/icon_tags.imageset/Contents.json
  Simplenote/Images.xcassets/icon_tags.imageset/tags.png
  Simplenote/Images.xcassets/icon_tags.imageset/tags@2x.png
  Simplenote/Images.xcassets/icon_tags.imageset/tags@3x.png
  Simplenote/Simplenote-DB5.plist
Labels: debt

#494 AppDelegate: Removing scrollView IBOutlet
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/en.lproj/MainMenu.xib
Labels: debt

#501 Implementing Autolayout. Part I
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/SPToolbarView.m
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/en.lproj/MainMenu.xib
Labels: debt

#507 Analytics: User Defaults
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Bundle+Simplenote.swift
  Simplenote/CrashLogging.swift
  Simplenote/MigrationsHandler.swift
  Simplenote/Options.swift
  Simplenote/Preferences.m
  Simplenote/PrivacyViewController.swift
  Simplenote/SPTracker.m
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/UserDefaults+Simplenote.swift
Labels: debt

#503 Refreshing Tags List: Part 0
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSImage+Colorize.h
  Simplenote/NSImage+Colorize.m
  Simplenote/NSImage+Simplenote.swift
  Simplenote/NSString+Styling.m
  Simplenote/NSTableView+Simplenote.swift
  Simplenote/NSTableViewCell+Simplenote.swift
  Simplenote/SPButtonNoBackground.h
  Simplenote/SPButtonNoBackground.m
  Simplenote/SPNoteCellView.m
  Simplenote/SPPopUpButton.h
  Simplenote/SPPopUpButton.m
  Simplenote/SPPopUpButtonCell.h
  Simplenote/SPPopUpButtonCell.m
  Simplenote/SPTagCellView.h
  Simplenote/SPTagCellView.m
  Simplenote/SPTextAttachment.swift
  Simplenote/SPTextView.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
Labels: debt, spring cleaning

#508 Merge release/1.10 into develop
  config/Version.public.xcconfig
Labels: Releases

#502 Refreshing Tags List: Part I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/HeaderTableCellView.swift
  Simplenote/Images.xcassets/Buttons/Contents.json
  Simplenote/Images.xcassets/Buttons/button_all_notes.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_all_notes.imageset/button_all_notes.pdf
  Simplenote/Images.xcassets/Buttons/button_trash.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_trash.imageset/button_trash.pdf
  Simplenote/Images.xcassets/icon_all_notes.imageset/Contents.json
  Simplenote/Images.xcassets/icon_all_notes.imageset/notes.png
  Simplenote/Images.xcassets/icon_all_notes.imageset/notes@2x.png
  Simplenote/Images.xcassets/icon_all_notes.imageset/notes@3x.png
  Simplenote/Images.xcassets/icon_all_notes.imageset/notes_dark_mojave.png
  Simplenote/Images.xcassets/icon_all_notes.imageset/notes_dark_mojave@2x.png
  Simplenote/Images.xcassets/icon_all_notes_dark.imageset/Contents.json
  Simplenote/Images.xcassets/icon_all_notes_dark.imageset/icon_notes_dark.png
  Simplenote/Images.xcassets/icon_all_notes_dark.imageset/icon_notes_dark@2x.png
  Simplenote/Images.xcassets/icon_all_notes_dark.imageset/icon_notes_dark@3x.png
  Simplenote/Images.xcassets/icon_all_notes_highlighted.imageset/Contents.json
  Simplenote/Images.xcassets/icon_all_notes_highlighted.imageset/notes_highlighted.png
  Simplenote/Images.xcassets/icon_all_notes_highlighted.imageset/notes_highlighted@2x.png
  Simplenote/Images.xcassets/icon_all_notes_highlighted.imageset/notes_highlighted@3x.png
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/SPNoteCellView.m
  Simplenote/SPTagCellView.h
  Simplenote/SPTagCellView.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#505 Refreshing Tags List: Part II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSColor+Studio.swift
  Simplenote/NoteListViewController.m
  Simplenote/SPTableRowView.h
  Simplenote/SPTableRowView.m
  Simplenote/SPTagTextField.m
  Simplenote/TableRowView.swift
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#510 Refreshing Tags List: Part III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSColor+Studio.swift
  Simplenote/NSImageView+Simplenote.swift
  Simplenote/SPTagTextField.h
  Simplenote/SPTagTextField.m
  Simplenote/SPTextField.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#498 Issue/notarization
  Gemfile.lock
  Simplenote.xcodeproj/project.pbxproj
Labels: tooling

#515 SPWindow: Displaying the title bar
  Simplenote/SPWindow.h
  Simplenote/SPWindow.m
Labels: spring cleaning

#511 Dropping SPToolbar: Mark 1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSAppearance+Simplenote.swift
  Simplenote/NSButton+Simplenote.swift
  Simplenote/NSColor+Studio.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SPToolbarView.h
  Simplenote/SPToolbarView.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#512 Dropping SPToolbarView: Mark 2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/SPToolbarView.h
  Simplenote/SPToolbarView.m
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/ToolbarState.swift
  Simplenote/ToolbarView.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#513 Dropping WKWebView initialization from Simplenote's App Delegate
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/MarkdownViewController.swift
  Simplenote/MarkdownViewController.xib
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning
