Repository Automattic/simplenote-macos, pull requests merged in 2020-12, with the labels that each got.

#730 Merge Release/2.5 back into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#731 Implements SplitItemMetrics
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/SplitItemMetrics.swift
  Simplenote/TagListViewController+Swift.swift
Labels: spring cleaning

#732 Notes List: Disables Desktop Tinting in Light Mode
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSBox+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
Labels: spring cleaning

#727 Taglist: Fixing Resize
  Simplenote/Main.storyboard
  Simplenote/TagListViewController+Swift.swift
Labels: bug

#734 Preventing Title Overlap
  Simplenote/Main.storyboard
  Simplenote/NSWindow+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SplitItemMetrics.swift
Labels: spring cleaning

#736 Merge Release/2.5 back into develop
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/NSBox+Simplenote.swift
  Simplenote/NSWindow+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SplitItemMetrics.swift
  Simplenote/TagListViewController+Swift.swift
  config/Version.public.xcconfig
Labels: Releases

#740 Adds missing Search Action
  Simplenote/Main.storyboard
Labels: [priority] high

#737 Toolbar: Sidebar Action
  RELEASE-NOTES.txt
  Simplenote/Main.storyboard
  Simplenote/NSWindow+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/ToolbarView.swift
Labels: spring cleaning

#741 Toolbar: Search Button
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AppKitConstants.swift
  Simplenote/Images.xcassets/Buttons/button_search.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_search.imageset/button_search.pdf
  Simplenote/Main.storyboard
  Simplenote/NSAnimationContext+Simplenote.swift
  Simplenote/NSView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.m
  Simplenote/ToolbarState.swift
  Simplenote/ToolbarView.swift
Labels: spring cleaning

#745 New Big Sur AppIcons
  RELEASE-NOTES.txt
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Contents.json
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-1024x1024.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-128x128.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-16x16.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-256x256-1.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-256x256.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-32x32-1.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-32x32.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-512x512-1.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-512x512.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-64x64.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_128x128.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_128x128@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_16x16.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_16x16@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_256x256.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_256x256@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_32x32.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_32x32@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_512x512.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_512x512@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Contents.json
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-128x128.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-128x128@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-16x16.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-16x16@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-256x256.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-256x256@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-32x32.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-32x32@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-512x512.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-512x512@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_128x128.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_128x128@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_16x16.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_16x16@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_256x256.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_256x256@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_32x32.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_32x32@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_512x512.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon_512x512@2x.png
  Simplenote/Simplenote-Info-Hockey.plist
Labels: spring cleaning

#746 Window Semaphore: Alignment!
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/Main.storyboard
  Simplenote/MainWindowController.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SplitViewController.swift
  Simplenote/Window.swift
Labels: spring cleaning

#748 Updates Color Palette 🎨
  RELEASE-NOTES.txt
  Simplenote/NSColor+Theme.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.m
  Simplenote/NoteTableCellView.swift
  Simplenote/TableRowView.swift
  Simplenote/TagTableCellView.swift
  Simplenote/ToolbarView.swift
Labels: spring cleaning

#754 Big Sur: Fixing Multiple Selection
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSBezierPath+Simplenote.swift
  Simplenote/TableRowView.swift
Labels: bug, spring cleaning

#751 Simperium Initialization Sequence
  .configure
  .configure-files/SPCredentials.swift.enc
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  Simplenote/SPCredentials-demo.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
Labels: [feature] search

#755 Notes List: New Sort Modes
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/NSSortDescriptor+Simplenote.swift
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.m
  Simplenote/Options.swift
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SortMode.swift
  Simplenote/UserDefaults+Simplenote.swift
  SimplenoteTests/NSUserDefaults+Tests.swift
  SimplenoteTests/OptionsTests.swift
Labels: [feature] note list

#758 Notes List: Separators
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/NSColor+Theme.swift
  Simplenote/NSEdgeInsets+Simplenote.swift
  Simplenote/TableRowView.swift
Labels: spring cleaning

#752 Debt: Initial Setup Flow
  Simplenote/AppKitConstants.swift
  Simplenote/Options.swift
  Simplenote/SPBucket+Simplenote.swift
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SimplenoteConstants.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: debt

#760 Implementing NotesListController: Mark I
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NotesListFilter.swift
  Simplenote/NotesListState.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/TagListRow+Filters.swift
  Simplenote/TagListRow.swift
  Simplenote/TagListViewController+Swift.swift
Labels: [feature] search

#763 Implementing NotesListController: Mark II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/NotesListController.swift
  SimplenoteTests/MockupStorage+Sample.swift
  SimplenoteTests/MockupStorage.swift
  SimplenoteTests/NotesListControllerTests.swift
Labels: [feature] search

#764 Implementing NotesListController: Mark III
  RELEASE-NOTES.txt
  Simplenote/Main.storyboard
  Simplenote/NSTableView+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.m
Labels: [feature] search, debt

#765 Implementing NotesListController: Mark IV
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/NSTableView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
Labels: [feature] search, debt

#766 Nukes dead code
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/NotesArrayController.h
  Simplenote/NotesArrayController.m
Labels: debt

#780 Implementing NotesListController: Mark V
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteListController.swift
  Simplenote/NoteListFilter.swift
  Simplenote/NoteListState.swift
  Simplenote/NoteListViewController.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/TagListRow+Filters.swift
  Simplenote/TagListViewController+Swift.swift
  SimplenoteTests/NoteListControllerTests.swift
Labels: [feature] search

#781 Implementing NoteListController: Mark VI
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteListController.swift
  Simplenote/NoteListFilter.swift
  Simplenote/NoteListState.swift
  Simplenote/NoteListViewController.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/TagListFilter.swift
  Simplenote/TagListRow+Filters.swift
  Simplenote/TagListRow.swift
  Simplenote/TagListViewController+Swift.swift
  SimplenoteTests/NoteListControllerTests.swift
Labels: [feature] search

#782 Updates SimplenoteFoundation
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: [feature] search

#768 Fixing Unexpected TagsList Jump
  RELEASE-NOTES.txt
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: bug

#769 Refreshing Notes List on Tag Rename
  RELEASE-NOTES.txt
  Simplenote/NoteListViewController.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
Labels: bug

#772 Empty Document: Line Height
  External/Notepad/Storage.swift
  External/Notepad/Theme.swift
  RELEASE-NOTES.txt
  Simplenote/SPTextView.m
Labels: bug

#770 Displaying Notes List on Search
  RELEASE-NOTES.txt
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteListViewController.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SplitViewController.swift
  Simplenote/ToolbarView.swift
Labels: [feature] search

#774 TagList: Cursor
  Simplenote/TagTableCellView.swift
Labels: bug

#775 Editor: Drops direct frame manipulation
  Simplenote/NoteEditorViewController.m
  Simplenote/SPTextView.h
  Simplenote/SPTextView.m
Labels: debt

#777 Bugfix: Editor Scroller Insets
  RELEASE-NOTES.txt
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteListViewController.swift
  Simplenote/SplitItemMetrics.swift
Labels: bug

#784 Editor: Resetting TagsEditor Offset
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
Labels: bug

#779 Bugfix: SplitView Dimple
  RELEASE-NOTES.txt
  Simplenote/SplitViewController.swift
Labels: bug
