Repository Automattic/simplenote-macos, pull requests merged in 2020-01, with the labels that each got.

#431 Fixing Warnings
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote-AppStore.xcscheme
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote/Note.h
Labels: debt

#432 Nukes unused code
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSMutableAttributedString+Styling.h
  Simplenote/NSMutableAttributedString+Styling.m
  Simplenote/NSString+Condensing.h
  Simplenote/NSString+Condensing.m
  Simplenote/NSString+Escaping.h
  Simplenote/NSString+Escaping.m
  Simplenote/NSString+Metadata.h
  Simplenote/NSString+Metadata.m
  Simplenote/Note.m
  Simplenote/NoteEditorViewController.m
  Simplenote/SPIntegrityHelper.h
  Simplenote/SPIntegrityHelper.m
  Simplenote/SPTextLinkifier.h
  Simplenote/SPTextLinkifier.m
  Simplenote/SimplenoteAppDelegate.m
Labels: debt

#428 Updates Secrets Path
  Simplenote.xcodeproj/project.pbxproj
Labels: bug

#430 Fix: Multibyte Characters going AWOL
  External/Notepad/Storage.swift
  RELEASE-NOTES.txt
  Simplenote/SPTextView.m
Labels: [priority] high

#433 Storage: Performance Optimizations
  External/Notepad/Element.swift
  External/Notepad/Extensions.swift
  External/Notepad/Info.plist
  External/Notepad/Notepad-macOS.swift
  External/Notepad/Storage.swift
  External/Notepad/Style.swift
  External/Notepad/Theme.swift
  External/Notepad/UniversalTypes.swift
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSAttributedString+Simplenote.swift
  Simplenote/NoteEditorViewController.m
Labels: debt

#434 Fixing Checklists going AWOL
  External/Notepad/Storage.swift
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSAttributedString+Simplenote.swift
  Simplenote/NSMutableAttributedString+Simplenote.swift
Labels: bug

#437 MainMenu IB Cleanup
  Simplenote/en.lproj/MainMenu.xib
Labels: debt

#438 Localizing (Unlocalized) Strings
  Simplenote/NoteEditorViewController.m
  Simplenote/TagListViewController.m
Labels: debt

#441 Checklists: Dynamic Sizing
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSMutableAttributedString+Styling.h
  Simplenote/NSMutableAttributedString+Styling.m
  Simplenote/NSString+Styling.m
  Simplenote/NSTextStorage+Simplenote.swift
  Simplenote/SPTextAttachment.swift
  Simplenote/SPTextView.m
Labels: bug

#442 Merge release/1.9 into develop
  config/Version.public.xcconfig
Labels: Releases

#444 Privacy Policy UI
  Simplenote/Privacy.storyboard
  Simplenote/PrivacyViewController.swift
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
Labels: enhancement

#443 Merge release/1.9 into develop
  Simplenote/Privacy.storyboard
  Simplenote/PrivacyViewController.swift
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  config/Version.public.xcconfig
Labels: Releases

#446 Update Fastlane to 2.140.0
  Gemfile
  Gemfile.lock
Labels: tooling
