Repository Automattic/simplenote-macos, pull requests merged in 2020-05, with the labels that each got.

#520 Dropping VSTheme: Mark 1
  DB5/VSTheme.h
  DB5/VSTheme.m
  DB5/VSThemeManager.h
  DB5/VSThemeManager.m
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/MarkdownViewController.swift
  Simplenote/NSApplication+Simplenote.swift
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.m
  Simplenote/Options.swift
  Simplenote/PublishViewController.swift
  Simplenote/SPMarkdownParser.m
  Simplenote/SPNoteCellView.m
  Simplenote/SPTextView.m
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
  Simplenote/SPUserInterface.swift
  Simplenote/SPWindow.m
  Simplenote/ShareViewController.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/ThemeOption.swift
  Simplenote/ToolbarView.swift
  Simplenote/UserDefaults+Simplenote.swift
  Simplenote/VSTheme+Simplenote.h
  Simplenote/VSTheme+Simplenote.m
  Simplenote/VersionsViewController.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#524 New Color Scheme!
  External/Notepad/Theme.swift
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/HeaderTableCellView.swift
  Simplenote/MarkdownViewController.swift
  Simplenote/MarkdownViewController.xib
  Simplenote/NSColor+Studio.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSFont+Theme.swift
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSScreen+Simplenote.swift
  Simplenote/NSString+Simplenote.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorBottomBar.m
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/PublishViewController.swift
  Simplenote/SPBackgroundView.h
  Simplenote/SPBackgroundView.m
  Simplenote/SPGradientView.h
  Simplenote/SPGradientView.m
  Simplenote/SPMarkdownParser.m
  Simplenote/SPNoteCellView.m
  Simplenote/SPSplitView.m
  Simplenote/SPTokenField.h
  Simplenote/SPUserInterface.swift
  Simplenote/SPWindow.h
  Simplenote/SPWindow.m
  Simplenote/ShareViewController.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/ToolbarView.swift
  Simplenote/VersionsViewController.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#525 Dropping VSTheme: Mark III
  DB5/VSTheme.h
  DB5/VSTheme.m
  DB5/VSThemeLoader.h
  DB5/VSThemeLoader.m
  DB5/VSThemeManager.h
  DB5/VSThemeManager.m
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Simplenote-DB5.plist
Labels: debt, spring cleaning

#533 Adding Style Guidelines
  readme.md
Labels: documentation

#534 Visually center the About window on screen.
  Simplenote/SimplenoteAppDelegate.m
Labels: enhancement, spring cleaning

#535 About window should respond to the ESC key.
  Simplenote/About.storyboard
Labels: enhancement, spring cleaning

#537 Updates App Icon
  Simplenote/Icons.xcassets/AppIcon.appiconset/Contents.json
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-1024x1024.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-128x128.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-128x128@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-16x16.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-16x16@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-256x256-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-256x256.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-256x256@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-32x32-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-32x32.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-32x32@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-512x512-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-512x512.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-512x512@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-64x64.png
Labels: spring cleaning

#531 Drops NSMenuItem Outlets: Part I
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/en.lproj/MainMenu.xib
Labels: debt

#532 Implements NSSplitViewController (Yay!)
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/SPSplitView.h
  Simplenote/SPSplitView.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SplitView.swift
  Simplenote/SplitViewController.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: debt, spring cleaning

#538 Decoupling Tags List: Mark 1
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/UserDefaults+Simplenote.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#539 Decoupling Tags List: Mark 2
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#542 Refreshing Notes List: Mark 0
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSString+Condensing.h
  Simplenote/NSString+Condensing.m
  Simplenote/Note.h
  Simplenote/Note.m
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.m
  Simplenote/Options.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListViewController.m
  Simplenote/UserDefaults+Simplenote.swift
  SimplenoteTests/Constants.swift
  SimplenoteTests/NSStringCondensingTests.swift
Labels: spring cleaning

#541 Refreshing Notes List: Mark 1
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/icon_pin.pdf
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared.pdf
  Simplenote/Images.xcassets/icon_pin.imageset/Contents.json
  Simplenote/Images.xcassets/icon_pin.imageset/icon_pin.png
  Simplenote/Images.xcassets/icon_pin.imageset/icon_pin@2x.png
  Simplenote/Images.xcassets/icon_pin.imageset/icon_pin_dark_mojave.png
  Simplenote/Images.xcassets/icon_pin.imageset/icon_pin_dark_mojave@2x.png
  Simplenote/Images.xcassets/icon_pin_dark.imageset/Contents.json
  Simplenote/Images.xcassets/icon_pin_dark.imageset/icon_pin_dark.png
  Simplenote/Images.xcassets/icon_pin_dark.imageset/icon_pin_dark@2x.png
  Simplenote/Images.xcassets/icon_pin_dark.imageset/icon_pin_dark_mojave.png
  Simplenote/Images.xcassets/icon_pin_dark.imageset/icon_pin_dark_mojave@2x.png
  Simplenote/Images.xcassets/icon_pin_highlighted.imageset/Contents.json
  Simplenote/Images.xcassets/icon_pin_highlighted.imageset/icon_pin_highlighted.png
  Simplenote/Images.xcassets/icon_pin_highlighted.imageset/icon_pin_highlighted@2x.png
  Simplenote/Images.xcassets/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/icon_shared.imageset/icon_shared@1x.png
  Simplenote/Images.xcassets/icon_shared.imageset/icon_shared@2x.png
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NSString+Condensing.h
  Simplenote/NSString+Condensing.m
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/NoteTableCellView.swift
  Simplenote/SPNoteCellView.h
  Simplenote/SPNoteCellView.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#543 Refreshing Notes List: Mark 3
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NSMutableAttributedString+Styling.h
  Simplenote/NSMutableAttributedString+Styling.m
  Simplenote/NSRegularExpression+Simplenote.swift
  Simplenote/NSString+Simplenote.swift
  Simplenote/NSString+Styling.h
  Simplenote/NSString+Styling.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteTableCellView.swift
  Simplenote/SPTextAttachment.swift
  SimplenoteTests/NSRegularExpressionSimplenoteTests.swift
Labels: spring cleaning

#544 Adjusting Button Sizes
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/ToolbarView.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#545 Restoring Window Titlebar
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#547 Implements Top Dividers
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/BackgroundView.swift
  Simplenote/MarkdownViewController.swift
  Simplenote/MarkdownViewController.xib
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SPBackgroundView.h
  Simplenote/SPBackgroundView.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#548 Interface: Adjusting Metrics
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/ClipView.swift
  Simplenote/MarkdownViewController.swift
  Simplenote/MarkdownViewController.xib
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning
