Repository Automattic/simplenote-macos, pull requests merged in 2020-11, with the labels that each got.

#702 Merge release 2.3 into develop
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#705 Merge release 2.4 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#706 Convert text to markdown when copying to pasteboard
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/SPTextView+Swift.swift
Labels: [feature] checklist, [feature] editor, bug

#708 About: Updating Hiring Section
  Simplenote/About.storyboard
  Simplenote/AboutViewController.swift
Labels: enhancement

#712 Update SwiftLint to 0.41.0
  .swiftlint.yml
  Rakefile
  Simplenote/ColorStudio.swift
Labels: spring cleaning

#714 Merge release 2.4 into trunk
  CONTRIBUTING.md
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/HeaderTableCellView.swift
  Simplenote/InterlinkViewController.swift
  Simplenote/MetricTableViewCell.swift
  Simplenote/MetricsViewController.swift
  Simplenote/MetricsViewController.xib
  Simplenote/NSPasteboard+Simplenote.swift
  Simplenote/Note+Interlinks.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteMetrics.swift
  Simplenote/NumberFormatter+Simplenote.swift
  Simplenote/ReferenceTableViewCell.swift
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/SeparatorTableViewCell.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/TagListRow.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/en.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
  fastlane/metadata/it/release_notes.txt
Labels: Releases

#713 Merge release 2.4 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/metadata/it/release_notes.txt
Labels: Releases

#715 Upgrade CocoaPods and remove the specs repo
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
Labels: tooling

#717 Updates Dependencies
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: task

#719 Main Window: Drops titlebar
  RELEASE-NOTES.txt
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/Main.storyboard
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
Labels: spring cleaning

#720 New Toolbar Assets
  Simplenote/Images.xcassets/Buttons/button_ellipsis_outline.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_ellipsis_outline.imageset/button_ellipsis_outline.pdf
  Simplenote/Images.xcassets/Buttons/button_tags_close.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_tags_close.imageset/button_tags_close.pdf
  Simplenote/Images.xcassets/Buttons/button_tags_open.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_tags_open.imageset/button_tags_open.pdf
  Simplenote/Main.storyboard
  Simplenote/NSImageName+Simplenote.swift
Labels: spring cleaning

#721 Updates TableView Styles
  RELEASE-NOTES.txt
  Simplenote/InterlinkViewController.swift
  Simplenote/Main.storyboard
  Simplenote/MetricsViewController.swift
  Simplenote/NSTableView+Simplenote.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/NoteTableCellView.swift
  Simplenote/TableRowView.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.m
Labels: spring cleaning

#722 Relocating Search Bar
  RELEASE-NOTES.txt
  Simplenote/Main.storyboard
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TagListRow.swift
Labels: spring cleaning

#723 Dropping High Sierra support
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/LoginWindowController.m
  Simplenote/NSAppearance+Simplenote.swift
  Simplenote/NSApplication+Simplenote.swift
  Simplenote/NSButton+Simplenote.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSImageView+Simplenote.swift
  Simplenote/NSVisualEffectView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/SPUserInterface.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SplitView.swift
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/ToolbarView.swift
  Simplenote/Window.swift
Labels: debt

#724 Header: Blur!
  External/Notepad/Theme.swift
  RELEASE-NOTES.txt
  Simplenote/Main.storyboard
  Simplenote/MarkdownViewController.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSString+Simplenote.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteListViewController.h
  Simplenote/NoteListViewController.m
  Simplenote/NoteTableCellView.swift
  Simplenote/SplitView.swift
  Simplenote/TagListViewController+Swift.swift
Labels: spring cleaning

#726 Bugfix: Title Hugging
  Simplenote/Main.storyboard
Labels: bug

#725 Bugfix: Metrics Width
  RELEASE-NOTES.txt
  Simplenote/MetricsViewController.swift
Labels: bug

#728 Editor: Fixing Initial Offset
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/NSScrollView+Simplenote.swift
  Simplenote/NoteEditorViewController.m
Labels: bug
