Repository Automattic/simplenote-macos, pull requests merged in 2020-07, with the labels that each got.

#570 New Metrics Screen: Mark 1
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/MetricsController.swift
  Simplenote/MetricsViewController.swift
  Simplenote/MetricsViewController.xib
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/ToolbarState.swift
  Simplenote/ToolbarView.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#575 New Metrics Screen: Mark 2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/DateFormatter+Simplenote.swift
  Simplenote/EntityObserver.swift
  Simplenote/MetricsController.swift
  Simplenote/MetricsViewController.swift
  Simplenote/MigrationsHandler.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteListViewController+Swift.swift
  Simplenote/NoteMetrics.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
Labels: spring cleaning

#578 Share Popover Style
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/ShareViewController.swift
  Simplenote/ShareViewController.xib
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#583 Merge hotfix 1.11.1 into main
  RELEASE-NOTES.txt
  Simplenote/About.storyboard
  Simplenote/AboutViewController.swift
  config/Version.public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#579 Publish Popover Style
  Simplenote/EntityObserver.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/PublishViewController.swift
  Simplenote/PublishViewController.xib
Labels: spring cleaning

#589 Tags Editor: Tab Support
  Simplenote/NoteEditorViewController+Swift.swift
Labels: bug

#582 Merge hotfix 1.11.1 into develop
  RELEASE-NOTES.txt
  Simplenote/About.storyboard
  Simplenote/AboutViewController.swift
  config/Version.public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#580 Versions Popover Style
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/DateFormatter+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/Simperium+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/Version.swift
  Simplenote/VersionsController.swift
  Simplenote/VersionsViewController.swift
  Simplenote/VersionsViewController.xib
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#585 Refreshing Toolbar Actions
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/CollaborateViewController.swift
  Simplenote/CollaborateViewController.xib
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/ToolbarState.swift
  Simplenote/ToolbarView.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#588 RTL Support: Tags Editor
  RELEASE-NOTES.txt
  Simplenote/TagAttachmentCell.swift
  Simplenote/en.lproj/MainMenu.xib
Labels: spring cleaning

#592 Merge 1.12.0 beta 1 into develop
  config/Version.public.xcconfig
Labels: Releases

#587 Reversing Markdown Preview Icon
  Simplenote/ToolbarState.swift
Labels: bug

#594 Updates release notes
  RELEASE-NOTES.txt
Labels: documentation

#593 Version Slider - Update UI after receiving an update for a currently selected version
  Simplenote/VersionsViewController.swift
Labels: enhancement

#598 Prevents presenting multiple Metrics Popovers
  Simplenote/NoteEditorViewController+Swift.swift
Labels: bug

#597 Fix: Negative word count
  Simplenote/NoteMetrics.swift
Labels: bug

#599 Fixing Trash System Menu Validation
  Simplenote/NoteEditorViewController+Swift.swift
Labels: bug

#602 Localizations Downloader
  Scripts/fix-translation
  Scripts/update-translations.rb
Labels: i18n

#604 TagListViewController: Replaces extraContentInsets mechanism
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/ClipView.swift
  Simplenote/NSWindow+Simplenote.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/en.lproj/MainMenu.xib
Labels: bug

#606 Localizing MainMenu XIB
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/en.lproj/MainMenu.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
Labels: i18n

#605 NIB(s) Localization Support
  Scripts/fix-translation
  Scripts/fix-translation.swift
  Scripts/localize.py
  Scripts/update-translations.rb
Labels: i18n, tooling

#613 Localization Script: Picking up Simperium Strings
  Scripts/localize.py
Labels: i18n, tooling

#611 Fastlane: Localization Step(s)
  Gemfile.lock
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/appstoreres/metadata/source/description.txt
  fastlane/appstoreres/metadata/source/keywords.txt
  fastlane/appstoreres/metadata/source/subtitle.txt
Labels: i18n, tooling

#617 Tags Validation
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSNotification+Simplenote.swift
  Simplenote/NSString+Simplenote.swift
  Simplenote/NSTableView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/SimplenoteConstants.swift
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/TagTextFormatter.swift
  SimplenoteTests/NSStringSimplenoteTests.swift
Labels: [feature] tags, enhancement
