Repository Automattic/simplenote-macos, pull requests merged in 2021-04, with the labels that each got.

#925 Merge 2.10 into develop 🚀
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#932 Merge release 2.11 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#940 AuthViewController: SignUp by default
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.m
Labels: enhancement

#941 MainWindowController: Enabling movableByBackground
  Simplenote/BackgroundView.swift
  Simplenote/MainWindowController.swift
  Simplenote/NoteListViewController.swift
  Simplenote/ToolbarView.swift
Labels: enhancement

#942 Updated copy for check email prompt
  Simplenote/SignupVerificationViewController.swift
Labels: enhancement

#895 Add lane to deploy to App Store and publish to GitHub
  .circleci/config.yml
  .configure
  .configure-files/app_store_connect_fastlane_api_key.json.enc
  .configure-files/google_cloud_keys.json.enc
  .gitignore
  Gemfile.lock
  Simplenote.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/env/user.env-example
Labels: tooling

#945 Merge 2.11 into develop
  .circleci/config.yml
  .configure
  .configure-files/app_store_connect_fastlane_api_key.json.enc
  .configure-files/google_cloud_keys.json.enc
  .gitignore
  Gemfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.m
  Simplenote/BackgroundView.swift
  Simplenote/MainWindowController.swift
  Simplenote/NoteListViewController.swift
  Simplenote/ToolbarView.swift
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/env/user.env-example
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#948 Merge 2.12 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#950 Merge develop into release/2.12
  .circleci/config.yml
  .configure
  .configure-files/app_store_connect_fastlane_api_key.json.enc
  .configure-files/google_cloud_keys.json.enc
  .gitignore
  Gemfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.m
  Simplenote/BackgroundView.swift
  Simplenote/MainWindowController.swift
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/ToolbarView.swift
  SimplenoteTests/NSTextViewSimplenoteTests.swift
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/env/user.env-example
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#947 Test Checklist: Adding more consistency
  TESTING-CHECKLIST.md
Labels: [feature] checklist

#953 Added a `setup` test, asking to sign up using mixed-capitalization
  TESTING-CHECKLIST.md
Labels: [feature] checklist

#952 Merge 2.12 beta 2 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/metadata/it/release_notes.txt
Labels: Releases

#927 Add logic to trigger App Store & GitHub upload via CircleCI APIs
  .circleci/config.yml
  Gemfile.lock
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/env/user.env-example
Labels: tooling
