Repository Automattic/simplenote-macos, pull requests merged in 2021-03, with the labels that each got.

#870 Use Fastlane on CI to run the tests and build the app
  .circleci/config.yml
  Gemfile.lock
  Simplenote/NoteListViewController.swift
  fastlane/Fastfile
Labels: tooling

#885 Merge finalized release 2.8 into develop
  .configure
  .configure-files/SPCredentials.swift.enc
  .gitignore
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
Labels: Releases

#889 Dropping Login Inheritance
  Simplenote/LoginWindowController.h
  Simplenote/LoginWindowController.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
Labels: debt

#860 Adjusted two obsolete tests
  TESTING-CHECKLIST.md
Labels: documentation

#887 Keyboard Shortcuts: MK1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/FileStorage.swift
  Simplenote/NSEvent+Simplenote.swift
  Simplenote/NSString+Metadata.h
  Simplenote/NSString+Metadata.m
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorMetadata.swift
  Simplenote/NoteEditorMetadataCache.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/SPApplication.h
  Simplenote/SPApplication.m
  Simplenote/SPApplication.swift
  Simplenote/SPTextView.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SplitViewController.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagsField.swift
Labels: accessibility

#888 Keyboard Shortcuts: MK2
  RELEASE-NOTES.txt
  Simplenote/Main.storyboard
  Simplenote/NSColor+Theme.swift
  Simplenote/NSTableView+Simplenote.swift
  Simplenote/NoteEditorMetadata.swift
  Simplenote/NoteEditorMetadataCache.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/SPApplication.swift
  Simplenote/SPTracker+Swift.swift
  Simplenote/Simperium+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/TableRowView.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
  Simplenote/TagTableCellView.swift
  Simplenote/Window.swift
Labels: accessibility

#899 [Tooling] Mark *.enc configure files as binary
  .gitattributes
Labels: tooling

#890 New Auth Flow
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Array+Simplenote.swift
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthWindowController.swift
  Simplenote/LoginWindowController.h
  Simplenote/LoginWindowController.m
  Simplenote/NSColor+Theme.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SimplenoteConstants.swift
Labels: [feature] security

#894 New Auth Flow: Mk2
  .configure
  .configure-files/SPCredentials.swift.enc
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AccountVerificationRemote.swift
  Simplenote/AppKitConstants.swift
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/MagicLinkAuthenticator.swift
  Simplenote/NSMutableAttributedString+Simplenote.swift
  Simplenote/NSWindow+Transitions.swift
  Simplenote/RemoteConstants.swift
  Simplenote/SPCredentials-demo.swift
  Simplenote/SignupRemote.swift
  Simplenote/SignupVerificationViewController.swift
  Simplenote/SignupVerificationViewController.xib
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SimplenoteConstants.swift
Labels: [feature] security

#898 Drops Welcome Note
  Simplenote/Options.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SimplenoteConstants.swift
  Simplenote/UserDefaults+Simplenote.swift
  Simplenote/en.lproj/Localizable.strings
Labels: debt

#902 Merge version 2.9 beta 1 into develop
  RELEASE-NOTES.txt
  Scripts/extract_release_notes.rb
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  Simplenote/en.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#901 Simperium: Nullability
  Podfile.lock
  Simplenote/Simperium+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
Labels: debt

#900 Fix: AuthTextField UI Glitch
  Podfile
  Podfile.lock
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/Simperium+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
Labels: bug

#911 Add .editorconfig
  .editorconfig
Labels: tooling

#909 Adding tests for new shortcuts introduced in 2.9
  TESTING-CHECKLIST.md
Labels: documentation

#912 Merge finalized release 2.9 into develop
  Simplenote/SignupVerificationViewController.swift
  Simplenote/SignupVerificationViewController.xib
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
Labels: Releases

#917 Merge 2.10 beta 1 into develop
  RELEASE-NOTES.txt
  Scripts/extract_release_notes.rb
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#922 Window: Miniaturize (OR) Zoom behavior on double click
  Simplenote/Window.swift
Labels: bug

#921 Bugfix: SearchField + Double Click
  RELEASE-NOTES.txt
  Simplenote/MainWindowController.swift
  Simplenote/SplitViewController.swift
  Simplenote/Window.swift
Labels: bug
