Repository Automattic/simplenote-macos, pull requests merged in 2021-08, with the labels that each got.

#1007 Setup RuboCop
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
Labels: tooling

#1011 Move Fastlane secrets outside of repository
  .configure
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/Pluginfile
Labels: tooling

#1012 Move swift secrets outside of the repository
  .circleci/config.yml
  .configure
  Scripts/Build-Phases/copy-secret.sh
  Scripts/Build-Phases/copy-secret.xcfilelist
  Simplenote.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: tooling

#1015 Merge 2.14 final to develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1017 Issue/password verification
  RELEASE-NOTES.txt
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
Labels: enhancement

#1013 In App Account Deletion
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AccountDeletionController.swift
  Simplenote/AccountRemote.swift
  Simplenote/AccountVerificationController.swift
  Simplenote/AccountVerificationRemote.swift
  Simplenote/AccountVerificationViewController.swift
  Simplenote/AuthViewController+Swift.swift
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/Date+Simplenote.swift
  Simplenote/NSAlert+Simplenote.swift
  Simplenote/Remote.swift
  Simplenote/RemoteError.swift
  Simplenote/SPTracker+Swift.swift
  Simplenote/SignupRemote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SimplenoteConstants.swift
  SimplenoteTests/AccountVerificationController+TestHelpers.swift
  SimplenoteTests/AccountVerificationControllerTests.swift
  SimplenoteTests/AccountVerificationRemoteTests.swift
  SimplenoteTests/MockAccountVerificationRemote.swift
  SimplenoteTests/SignupRemoteTests.swift
Labels: enhancement, [feature] settings

#1019 Adds account verification response to login flow
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.m
  Simplenote/NSProgressIndicator+Simplenote.swift
Labels: enhancement, [feature] email verification

#1022 Merge 2.15 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  Simplenote/en.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases
