Repository Automattic/simplenote-macos, pull requests merged in 2021-10, with the labels that each got.

#1042 Preferences View Controller and UI
  External/Notepad/Theme.swift
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AppKitConstants.swift
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/FontSettings.swift
  Simplenote/Images.xcassets/Buttons/button_settings.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_settings.imageset/settings.svg
  Simplenote/NSButton+Extensions.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSStoryboard+Simplenote.swift
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/Options.swift
  Simplenote/Preferences.storyboard
  Simplenote/PreferencesViewController.swift
  Simplenote/SPTracker+Swift.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/TagListRow.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/ThemeOption.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: enhancement, [feature] settings

#1044 Copy Secrets: Preventing Overwork
  Scripts/Build-Phases/copy-secret.sh
Labels: tooling

#1049 Merge 2.16 final to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/en.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases
