Repository Automattic/simplenote-macos, pull requests merged in 2021-07, with the labels that each got.

#980 Breadcrumbs
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/BreadcrumbsViewController.swift
  Simplenote/Images.xcassets/Icons/icon_disclosure_right.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_disclosure_right.imageset/icon_disclosure_right.pdf
  Simplenote/Main.storyboard
  Simplenote/NSColor+Theme.swift
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListFilter.swift
  Simplenote/NoteListViewController.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SplitItemMetrics.swift
  Simplenote/SplitViewController.swift
  Simplenote/TagListFilter.swift
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.h
  Simplenote/TagListViewController.m
Labels: enhancement

#987 Scrollable Tags Editor
  RELEASE-NOTES.txt
  Simplenote/HorizontalScrollView.swift
  Simplenote/Main.storyboard
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/SplitItemMetrics.swift
Labels: enhancement

#992 Bugfix: Focus Mode Launch + Status Bar
  Simplenote/TagListViewController+Swift.swift
  Simplenote/TagListViewController.m
Labels: bug

#988 StatusBar: Optionally Hidden
  RELEASE-NOTES.txt
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/Options.swift
  Simplenote/SPTracker+Swift.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SplitViewController.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: enhancement

#997 Insert Checklists Validation
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/ToolbarView.swift
Labels: enhancement

#1005 Fixing Format String
  Simplenote/BreadcrumbsViewController.swift
Labels: bug

#1004 Merge 2.14 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/BreadcrumbsViewController.swift
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  Simplenote/en.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1006 Track `Package.resolved` file
  Simplenote.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: tooling
