Repository Automattic/simplenote-macos, pull requests merged in 2021-01, with the labels that each got.

#776 Editor: Default Line Length
  RELEASE-NOTES.txt
  Simplenote/Options.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: enhancement

#785 Fixing Unexpected Jumpy Scroll
  RELEASE-NOTES.txt
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/SPTextView.m
Labels: bug

#794 Editor: Fixes unexpected Notes Jump behavior
  Simplenote/NoteEditorViewController+Swift.swift
Labels: bug

#787 Adjusting legacy macOS Window Semaphore Metrics
  Simplenote/MainWindowController.swift
Labels: spring cleaning

#786 Window: Restoring DoubleClick on Titlebar behavior
  RELEASE-NOTES.txt
  Simplenote/NSWindow+Simplenote.swift
  Simplenote/Window.swift
Labels: bug

#796 Fixing SplitView Restoration
  Simplenote/Main.storyboard
  Simplenote/MainWindowController.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
Labels: bug

#789 Search: Sortbar
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Images.xcassets/Icons/icon_chevron_down.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_chevron_down.imageset/icon_chevron_down.pdf
  Simplenote/Main.storyboard
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NSScrollView+Simplenote.swift
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/Options.swift
  Simplenote/SortBarView.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: [feature] search

#790 Notes: Sort Date
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/DateFormatter+Simplenote.swift
  Simplenote/NoteListPrefixFormatter.swift
  Simplenote/NoteListViewController.swift
  Simplenote/NoteTableCellView.swift
Labels: [feature] search

#791 Notes: Extra Bottom Insets
  Simplenote/NoteListViewController.swift
  Simplenote/SplitItemMetrics.swift
Labels: [feature] search

#792 Notes: Empty State
  Simplenote/NoteListViewController.swift
Labels: [feature] search

#793 New Toggle Sidebar Behavior
  RELEASE-NOTES.txt
  Simplenote/SplitViewController.swift
Labels: spring cleaning

#797 Merge release 2.6 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  Simplenote/en.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#798 [Platform] Update Tools and fix nokogiri vulnerability
  .ruby-version
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#799 New Beta Icons
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_128x128.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_128x128@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_16x16.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_16x16@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_256x256.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_256x256@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_32x32.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_32x32@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_512x512.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/icon_512x512@2x.png
Labels: spring cleaning

#801 Simperium: Sync'ing Account Entity
  .configure
  .configure-files/SPCredentials.swift.enc
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/EmailVerification.swift
  Simplenote/SPCredentials-demo.swift
  Simplenote/Simperium+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  SimplenoteTests/EmailVerificationTests.swift
Labels: [feature] security

#807 Email Verification UI
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AccountVerificationController.swift
  Simplenote/AccountVerificationViewController.swift
  Simplenote/AccountVerificationViewController.xib
  Simplenote/Button.swift
  Simplenote/Images.xcassets/Buttons/button_cross.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_cross.imageset/cross.pdf
  Simplenote/Images.xcassets/Icons/icon_mail.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_mail.imageset/icon_mail.pdf
  Simplenote/NSColor+Theme.swift
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/SPTracker+Swift.swift
  Simplenote/SPTracker.h
  Simplenote/SimplenoteConstants.swift
Labels: [feature] security

#809 Implements AccountVerification Remote
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AccountVerificationRemote.swift
  Simplenote/SimplenoteConstants.swift
  SimplenoteTests/AccountVerificationRemoteTests.swift
  SimplenoteTests/MockStorage+Sample.swift
  SimplenoteTests/MockStorage.swift
  SimplenoteTests/MockTextView.swift
  SimplenoteTests/MockURLSession.swift
  SimplenoteTests/MockURLSessionDataTask.swift
  SimplenoteTests/NSTextViewSimplenoteTests.swift
  SimplenoteTests/NoteListControllerTests.swift
  SimplenoteTests/TextViewInputHandlerTests.swift
Labels: [feature] security

#810 Implements AccountVerification Controller
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AccountVerificationController.swift
  Simplenote/AccountVerificationCoordinator.swift
  Simplenote/AccountVerificationViewController.swift
  Simplenote/Simperium+Simplenote.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  SimplenoteTests/AccountVerificationControllerTests.swift
  SimplenoteTests/MockAccountVerificationRemote.swift
Labels: [feature] security

#811 Merge finalized release 2.6 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#823 Optimized Assets
  Simplenote/Images.xcassets/Buttons/button_all_notes.imageset/button_all_notes.pdf
  Simplenote/Images.xcassets/Buttons/button_cross.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_cross.imageset/button_cross.pdf
  Simplenote/Images.xcassets/Buttons/button_cross.imageset/cross.pdf
  Simplenote/Images.xcassets/Buttons/button_ellipsis.imageset/button_ellipsis.pdf
  Simplenote/Images.xcassets/Buttons/button_ellipsis_outline.imageset/button_ellipsis_outline.pdf
  Simplenote/Images.xcassets/Buttons/button_history.imageset/button_history.pdf
  Simplenote/Images.xcassets/Buttons/button_info.imageset/button_info.pdf
  Simplenote/Images.xcassets/Buttons/button_new_note.imageset/button_new_note.pdf
  Simplenote/Images.xcassets/Buttons/button_preview_off.imageset/button_preview_off.pdf
  Simplenote/Images.xcassets/Buttons/button_preview_on.imageset/button_preview_on.pdf
  Simplenote/Images.xcassets/Buttons/button_restore.imageset/button_restore.pdf
  Simplenote/Images.xcassets/Buttons/button_search.imageset/button_search.pdf
  Simplenote/Images.xcassets/Buttons/button_share.imageset/button_share.pdf
  Simplenote/Images.xcassets/Buttons/button_tags_close.imageset/button_tags_close.pdf
  Simplenote/Images.xcassets/Buttons/button_tags_open.imageset/button_tags_open.pdf
  Simplenote/Images.xcassets/Buttons/button_trash.imageset/button_trash.pdf
  Simplenote/Images.xcassets/Buttons/button_untagged.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_untagged.imageset/button_untagged.pdf
  Simplenote/Images.xcassets/Buttons/button_untagged.imageset/icon_untagged.pdf
  Simplenote/Images.xcassets/Icons/icon_arrow_top_right.imageset/icon_arrow_top_right.pdf
  Simplenote/Images.xcassets/Icons/icon_mail.imageset/icon_mail.pdf
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared.pdf
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/icon_task_checked.pdf
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/icon_task_unchecked.pdf
Labels: enhancement

#822 Email Verification: Preventing UI Resize
  Simplenote/AccountVerificationViewController.xib
Labels: bug
