Repository Automattic/simplenote-macos, pull requests merged in 2021-11, with the labels that each got.

#1051 Merge 2.17 final to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1045 Feature/preferences
  External/Notepad/Theme.swift
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AccountDeletionController.swift
  Simplenote/AppKitConstants.swift
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/FontSettings.swift
  Simplenote/Images.xcassets/Buttons/button_settings.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_settings.imageset/settings.svg
  Simplenote/NSAlert+Simplenote.swift
  Simplenote/NSButton+Extensions.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NSNotification+Simplenote.h
  Simplenote/NSNotification+Simplenote.m
  Simplenote/NSStoryboard+Simplenote.swift
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/Options.swift
  Simplenote/Preferences.storyboard
  Simplenote/PreferencesViewController.swift
  Simplenote/SPTracker+Swift.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/ThemeOption.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: enhancement, [feature] settings

#1053 fixed release notes for preferences
  RELEASE-NOTES.txt
Labels: [feature] settings

#1054 Increases no_output_timeout for CircleCI test job to 3m
  .circleci/config.yml
Labels: tooling

#1055 Remove pr list generation at code freeze
  fastlane/Fastfile
Labels: tooling
