Repository Automattic/simplenote-macos, pull requests merged in 2021-02, with the labels that each got.

#832 AccountVerificationController: Case insensitive comparison
  Simplenote/AccountVerificationController.swift
Labels: [priority] high

#829 Remove duplicated default timeout definition from unit tests
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteTests/Constants.swift
  SimplenoteTests/NSAttributedStringSimplenoteTests.swift
  SimplenoteTests/TestConstants.swift
Labels: spring cleaning

#825 Adds Logout Divider
  Simplenote/Base.lproj/MainMenu.xib
Labels: enhancement

#831 SortBar: Always visible
  RELEASE-NOTES.txt
  Simplenote/NoteListViewController.swift
  Simplenote/Options.swift
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
  Simplenote/UserDefaults+Simplenote.swift
Labels: [feature] search

#830 Show relevant excerpts while searching
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/ContentSlice.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSString+Condensing.h
  Simplenote/NSString+Condensing.m
  Simplenote/Note+Simplenote.swift
  Simplenote/Note.h
  Simplenote/Note.m
  Simplenote/NoteContentHelper.swift
  Simplenote/NoteListFilter.swift
  Simplenote/NoteListViewController.swift
  Simplenote/NoteTableCellView.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/String+Simplenote.swift
  SimplenoteTests/NSStringCondensingTests.swift
  SimplenoteTests/NoteBodyExcerptTests.swift
  SimplenoteTests/NoteListControllerTests.swift
  SimplenoteTests/StringContentSliceTests.swift
  SimplenoteTests/StringSimplenoteTests.swift
Labels: [feature] search

#833 Interface: Separators
  Simplenote/BackgroundView.swift
  Simplenote/Main.storyboard
  Simplenote/NSColor+Theme.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteListViewController.swift
  Simplenote/TagListViewController+Swift.swift
Labels: [feature] search

#835 Highlight search keywords in the editor
  External/Notepad/Storage.swift
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/NSColor+Theme.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/SPMarkdownParser.m
  Simplenote/SPTableView.h
  Simplenote/SPTextView+Swift.swift
  Simplenote/SPTextView.h
  Simplenote/SPTextView.m
  Simplenote/SPTextView.swift
Labels: [feature] editor, [feature] search

#836 Search map
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/SPTextView.swift
  Simplenote/SearchMapView.swift
Labels: [feature] editor, [feature] search

#838 Relocating Search Bar
  RELEASE-NOTES.txt
  Simplenote/Main.storyboard
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
  Simplenote/NoteListViewController.swift
  Simplenote/SPApplication.m
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/SplitViewController.swift
  Simplenote/ToolbarState.swift
  Simplenote/ToolbarView.swift
Labels: [feature] search

#839 Updating Sort Bar UX
  Simplenote/Base.lproj/MainMenu.xib
  Simplenote/Main.storyboard
  Simplenote/SortBarView.swift
  Simplenote/SortMode.swift
Labels: [feature] search

#844 Merge finalize version 2.7 into develop
  config/Version.public.xcconfig
Labels: Releases

#846 Update pin color on the note row
  Simplenote/NoteTableCellView.swift
Labels: enhancement

#847 Merge release 2.8 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  Simplenote/en.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#849 Improve text view performance
  External/Notepad/Storage.h
  External/Notepad/Storage.m
  External/Notepad/Storage.swift
  External/Notepad/Theme.swift
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NSTextView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/Simplenote-Bridging-Header.h
Labels: task

#840 Tags List: Adjusting Separator
  Simplenote/NSColor+Theme.swift
  Simplenote/TagListViewController.m
Labels: bug

#841 Window: Preventing zoom when double clicking the First Responder
  RELEASE-NOTES.txt
  Simplenote/Window.swift
Labels: bug

#850 Dropping Sort Bar
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Main.storyboard
  Simplenote/NoteListViewController.swift
  Simplenote/SortBarView.swift
Labels: enhancement

#852 Fixing AppStore Target
  Simplenote.xcodeproj/project.pbxproj
Labels: [priority] high

#851 Skinning Searchbar
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AppKitConstants.swift
  Simplenote/Main.storyboard
  Simplenote/NSColor+Theme.swift
  Simplenote/NSFont+Simplenote.swift
  Simplenote/NSImageName+Simplenote.swift
  Simplenote/NSView+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteListViewController.swift
  Simplenote/SearchField.swift
Labels: [feature] search

#857 Issue/update simplenote search version
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/NoteListViewController.swift
  Simplenote/SearchQuery+Simplenote.swift
Labels: enhancement

#867 Fix bundler in develop
  Gemfile
  Gemfile.lock
Labels: tooling

#868 Fix bundler in release 2.8
  Gemfile
  Gemfile.lock
Labels: tooling

#866 Pinning SimplenoteSearch to Mk 1.2.0
  Simplenote.xcodeproj/project.pbxproj
Labels: [priority] high

#863 Build App Store target on CI
  .circleci/config.yml
Labels: tooling

#871 Decoupling PopoverWindowController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Interlink.storyboard
  Simplenote/InterlinkViewController.xib
  Simplenote/NSStoryboard+Simplenote.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/PopoverWindow.swift
  Simplenote/PopoverWindowController.swift
Labels: debt

#872 Decoupling PopoverWindowController: Mk 2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/InterlinkProcessor.swift
  Simplenote/NoteEditorViewController+Swift.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/NoteEditorViewController.m
Labels: debt

#873 Decoupling PopoverWindowController: Mk 3
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/InterlinkProcessor.swift
  Simplenote/InterlinkResultsController.swift
  Simplenote/InterlinkViewController.swift
  Simplenote/InterlinkViewController.xib
  Simplenote/LinkTableCellView.swift
  Simplenote/NoteEditorViewController+Swift.swift
Labels: debt

#874 Add SearchQuery+Simplenote.swift to the App Store target
  Simplenote.xcodeproj/project.pbxproj
Labels: bug

#883 Update secrets
  .configure
  .configure-files/SPCredentials.swift.enc
  .configure-files/app_store_connect_fastlane_api_key.json
  .configure-files/google_cloud_keys.json
Labels: tooling
