Repository Automattic/simplenote-macos, pull requests merged in 2021-05, with the labels that each got.

#960 Updated signup remote to lowercase emails before sending to simperium
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/SignupRemote.swift
  SimplenoteTests/MockURLSession.swift
  SimplenoteTests/SignupRemoteTests.swift
  SimplenoteTests/URLRequest+Simplenote.swift
Labels: bug

#964 Fixing CI Unit Tests
  SimplenoteTests/SignupRemoteTests.swift
Labels: bug

#963 Merge finalized release 2.12 into develop
  .circleci/config.yml
  Gemfile.lock
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/env/user.env-example
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#961 Integrates Simperium Mk 1.8.0
  Podfile
  Podfile.lock
Labels: enhancement

#965 Merge release 2.13 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#967 Mapping Simperium Mk 1.8
  Podfile
  Podfile.lock
Labels: enhancement

#970 Execute tests in random order
  .circleci/config.yml
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
Labels: tooling

#974 Merge finalized release 2.13 into develop
  Podfile
  Podfile.lock
  config/Version.public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#975 Merge release 2.13 into trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/SignupRemote.swift
  SimplenoteTests/MockURLSession.swift
  SimplenoteTests/SignupRemoteTests.swift
  SimplenoteTests/URLRequest+Simplenote.swift
  TESTING-CHECKLIST.md
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/download_metadata.swift
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases
