Repository Automattic/simplenote-macos, pull requests merged in 2021-09, with the labels that each got.

#1025 Updated expected body for verification required
  Simplenote/AuthViewController.m
Labels: bug

#1026 Updated copy for account deletion alert message to include user email
  RELEASE-NOTES.txt
  Simplenote/AccountDeletionController.swift
Labels: enhancement

#1028 Merge 2.15 final to trunk
  RELEASE-NOTES.txt
  Simplenote/AccountDeletionController.swift
  Simplenote/AuthViewController.m
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1027 Merge 2.15 final to develop
  RELEASE-NOTES.txt
  Simplenote/AccountDeletionController.swift
  Simplenote/AuthViewController.m
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/ar.lproj/MainMenu.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/cy.lproj/MainMenu.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/de.lproj/MainMenu.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/el.lproj/MainMenu.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/es.lproj/MainMenu.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fa.lproj/MainMenu.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/fr.lproj/MainMenu.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/he.lproj/MainMenu.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/id.lproj/MainMenu.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/it.lproj/MainMenu.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ja.lproj/MainMenu.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/ko.lproj/MainMenu.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/nl.lproj/MainMenu.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/MainMenu.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/ru.lproj/MainMenu.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/sv.lproj/MainMenu.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/tr.lproj/MainMenu.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/MainMenu.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/MainMenu.strings
  config/Version.public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1031 Hotfix light mode window issue
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
Labels: bug

#1032 Merge hotfix 2.15.1 into `develop`
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  config/Version.public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#1035 Updates Readme
  readme.md
Labels: enhancement

#1043 Update strings for compromised password alert
  Simplenote/AuthViewController+Swift.swift
Labels: enhancement, [feature] security
