Repository Automattic/simplenote-macos, pull requests merged in 2024-07, with the labels that each got.

#1177 Updates linter rules
  .swiftlint.yml
Labels: debt

#1178 Magic Link Login: Mk 1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/LoginRemote.swift
  Simplenote/Remote.swift
  Simplenote/RemoteError.swift
  Simplenote/SimplenoteConstants.swift
  Simplenote/URLSessionProtocol.swift
  SimplenoteTests/LoginRemoteTests.swift
  SimplenoteTests/MockURLSession.swift
Labels: enhancement

#1179 Magic Link Login: Mk 2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/LoginRemoteProtocol.swift
  Simplenote/MagicLinkAuthenticator.swift
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
  Simplenote/SimperiumAuthenticatorProtocol.swift
  Simplenote/Simplenote-Info.plist
  SimplenoteTests/MagicLinkAuthenticatorTests.swift
  SimplenoteTests/MockLoginRemote.swift
  SimplenoteTests/MockSimperiumAuthenticator.swift
Labels: enhancement

#1180 Magic Link Login: Mk 3
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthenticationMode.swift
Labels: enhancement

#1186 Magic Link Login: Mk 3.1
  Simplenote.entitlements
  Simplenote/MagicLinkAuthenticator.swift
  Simplenote/PreferencesViewController.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteConstants.swift
  Simplenote/SimplenoteDebug.entitlements
Labels: enhancement

#1181 Magic Link Login: Mk 4
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.m
  Simplenote/AuthWindowController.swift
  Simplenote/MagicLinkAuthenticator.swift
  Simplenote/MagicLinkConfirmationView.swift
  Simplenote/MagicLinkRequestedView.swift
  Simplenote/NSWindow+Transitions.swift
  SimplenoteTests/MagicLinkAuthenticatorTests.swift
Labels: enhancement

#1188 Magic Links: Wires new Endpoints
  Simplenote/LoginRemote.swift
  Simplenote/LoginRemoteProtocol.swift
  Simplenote/MagicLinkAuthenticator.swift
  SimplenoteTests/LoginRemoteTests.swift
  SimplenoteTests/MagicLinkAuthenticatorTests.swift
  SimplenoteTests/MockLoginRemote.swift
Labels: enhancement

#1189 Magic Links: Adjusting Copy
  Simplenote/AuthViewController.m
  Simplenote/MagicLinkAuthenticator.swift
  Simplenote/MagicLinkConfirmationView.swift
  Simplenote/SPTracker.h
  Simplenote/SPTracker.m
Labels: enhancement

#1190 Charlie/passkey registration
  Simplenote.entitlements
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/BlockingActivityIndicator.swift
  Simplenote/NSAlert+Passkeys.swift
  Simplenote/PasskeyError.swift
  Simplenote/PasskeyRegistrationChallenge.swift
  Simplenote/PasskeyRegistrationResponse.swift
  Simplenote/PasskeyRegistrator.swift
  Simplenote/PasskeyTypeAliases.swift
  Simplenote/Preferences.storyboard
  Simplenote/PreferencesViewController.swift
  Simplenote/SimplenoteConstants.swift
  Simplenote/SimplenoteDebug.entitlements
  Simplenote/String+Simplenote.swift
  SimplenoteTests/PasskeyRemote.swift
Labels: [feature] login

#1191 Passkeys: Passkey authentication
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthenticationMode.swift
  Simplenote/Data+Simplenote.swift
  Simplenote/PasskeyAuthChallenge.swift
  Simplenote/PasskeyAuthResponse.swift
  Simplenote/PasskeyAuthenticator.swift
  Simplenote/PasskeyTypeAliases.swift
  Simplenote/PasskeyVerifyResponse.swift
  Simplenote/SimplenoteConstants.swift
  SimplenoteTests/PasskeyRemote.swift
Labels: [feature] login

#1193 Magic Links: Add SPNavigationController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthWindowController.swift
  Simplenote/AuthenticationMode.swift
  Simplenote/NSView+Simplenote.swift
  Simplenote/NSViewController+Simplenote.swift
  Simplenote/SPNavigationController.swift
Labels: [feature] login

#1194 Magic Links: UI Updates Mk1
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthenticationMode.swift
  Simplenote/NSColor+Theme.swift
Labels: [feature] login

#1196 Navigation Bar: Polishing Animation
  Simplenote/SPNavigationController.swift
Labels: enhancement

#1195 Magic Links: Refactor Authentication Mode to handle auth view definitions
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthenticationMode.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/UserDefaults+Simplenote.swift
Labels: [feature] login

#1197 Magic Links: Implement Code view and Password view
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthenticationMode.swift
  Simplenote/NSProgressIndicator+Simplenote.swift
  Simplenote/SignupVerificationViewController.swift
Labels: [feature] login

#1198 Magic links: Tweaks and updates
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthWindowController.swift
  Simplenote/AuthenticationMode.swift
  Simplenote/SPAuthenticationTextField+Simplenote.swift
  Simplenote/SPNavigationController.swift
Labels: [feature] login

#1199 Integrates SimplenoteEndpoints Swift Package
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/AccountDeletionController.swift
  Simplenote/AccountRemote.swift
  Simplenote/AccountVerificationController.swift
  Simplenote/AuthViewController+Swift.swift
  Simplenote/LoginRemote.swift
  Simplenote/LoginRemoteProtocol.swift
  Simplenote/MagicLinkAuthenticator.swift
  Simplenote/Remote.swift
  Simplenote/RemoteConstants.swift
  Simplenote/RemoteError.swift
  Simplenote/SignupRemote.swift
  Simplenote/SimperiumAuthenticatorProtocol.swift
  Simplenote/URLSessionProtocol.swift
  SimplenoteTests/AccountVerificationController+TestHelpers.swift
  SimplenoteTests/AccountVerificationControllerTests.swift
  SimplenoteTests/AccountVerificationRemoteTests.swift
  SimplenoteTests/LoginRemoteTests.swift
  SimplenoteTests/MagicLinkAuthenticatorTests.swift
  SimplenoteTests/MockAccountVerificationRemote.swift
  SimplenoteTests/MockLoginRemote.swift
  SimplenoteTests/MockURLSession.swift
  SimplenoteTests/SignupRemoteTests.swift
Labels: debt, [feature] security

#1200 Error Handling Upgrades
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthenticationError.swift
  Simplenote/AuthenticationMode.swift
Labels: debt, [feature] login

#1201 Authentication: Handling requestNotFound
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthViewController+Swift.swift
  Simplenote/NSAlert+AuthErrors.swift
Labels: enhancement

#1202 Authentication: Addressing Debt
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
Labels: debt

#1203 AuthenticationMode: RateLimiting Fallback
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthenticationMode.swift
Labels: [feature] login

#1204 Magic Links: Fix window resizing animation + some clean up
  Simplenote/SPNavigationController.swift
Labels: [feature] login

#1205 Magic Links: The one PR to rule them all
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/AccountDeletionController.swift
  Simplenote/AccountRemote.swift
  Simplenote/AccountVerificationController.swift
  Simplenote/AuthViewController+Swift.swift
  Simplenote/AuthViewController.h
  Simplenote/AuthViewController.m
  Simplenote/AuthViewController.xib
  Simplenote/AuthWindowController.swift
  Simplenote/AuthenticationError.swift
  Simplenote/AuthenticationMode.swift
  Simplenote/LoginRemote.swift
  Simplenote/LoginRemoteProtocol.swift
  Simplenote/MagicLinkAuthenticator.swift
  Simplenote/NSAlert+AuthErrors.swift
  Simplenote/NSColor+Theme.swift
  Simplenote/NSProgressIndicator+Simplenote.swift
  Simplenote/Remote.swift
  Simplenote/RemoteConstants.swift
  Simplenote/RemoteError.swift
  Simplenote/SPAuthenticationTextField+Simplenote.swift
  Simplenote/SPNavigationController.swift
  Simplenote/SignupRemote.swift
  Simplenote/SignupVerificationViewController.swift
  Simplenote/SimperiumAuthenticatorProtocol.swift
  Simplenote/URLSessionProtocol.swift
  Simplenote/UserDefaults+Simplenote.swift
  SimplenoteTests/AccountVerificationController+TestHelpers.swift
  SimplenoteTests/AccountVerificationControllerTests.swift
  SimplenoteTests/AccountVerificationRemoteTests.swift
  SimplenoteTests/LoginRemoteTests.swift
  SimplenoteTests/MagicLinkAuthenticatorTests.swift
  SimplenoteTests/MockAccountVerificationRemote.swift
  SimplenoteTests/MockLoginRemote.swift
  SimplenoteTests/MockURLSession.swift
  SimplenoteTests/SignupRemoteTests.swift
Labels: [feature] login

#1185 Add `Base.xcconfig` and push most code signing settings there
  Base.xcconfig
  Simplenote.xcodeproj/project.pbxproj
  config/Simplenote.debug.xcconfig
  config/Simplenote.release.xcconfig
Labels: tooling
