Repository Automattic/simplenote-macos, pull requests merged in 2024-05, with the labels that each got.

#1150 Fastlane `match`: Migrate Code Signing from Google Cloud to S3
  .configure
  .configure-files/app_store_connect_fastlane_api_key.json.enc
  .configure-files/google_cloud_keys.json.enc
  Gemfile.lock
  fastlane/Fastfile
  fastlane/env/user.env-example
Labels: tooling

#1152 Fixed issue where the navigation buttons were invisible in markdown view
  Simplenote/MarkdownViewController.swift
Labels: [feature] markdown

#1154 Merge 2.20.0.4 into trunk
  RELEASE-NOTES.txt
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/metadata/copyright.txt
  fastlane/metadata/default/marketing_url.txt
  fastlane/metadata/default/privacy_url.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
Labels: Releases

#1153 Add intents extension code signing
  fastlane/Fastfile
Labels: tooling

#1155 Added SimplenoteIntents extension to Simplenote Mac Project
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteIntents.xcscheme
  SimplenoteIntents/Info.plist
  SimplenoteIntents/IntentHandler.swift
  fastlane/Fastfile
Labels: [feature] shortcuts

#1164 added swiftlint warnings to appear in xcode
  Simplenote.xcodeproj/project.pbxproj
Labels: tooling

#1160 Shortcuts: Add open new note intent
  IntentsExtension/Info.plist
  IntentsExtension/IntentHandler.swift
  IntentsExtension/IntentHandlers/OpenNewNoteIntentHandler.swift
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/ActivityType.swift
  Simplenote/NoteEditorViewController.h
  Simplenote/ShortcutIntents.intentdefinition
  Simplenote/Simplenote-Info.plist
  Simplenote/SimplenoteAppDelegate+Swift.swift
Labels: [feature] shortcuts

#1161 Refactor core data
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/CoreDataManager.swift
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/StorageSettings.swift
Labels: tooling

#1162 Migrate database to group container
  IntentsExtension/Info.plist
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Bundle+Simplenote.swift
  Simplenote/CoreDataManager.swift
  Simplenote/CoreDataValidator.swift
  Simplenote/FileManager+Simplenote.swift
  Simplenote/FileManagerProtocol.swift
  Simplenote/SharedStorageMigrator.swift
  Simplenote/Simplenote-Info.plist
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SimplenoteAppDelegate.h
  Simplenote/SimplenoteAppDelegate.m
  Simplenote/StorageSettings.swift
  SimplenoteTests/MockFileManager.swift
  SimplenoteTests/MockStorageSettings.swift
  SimplenoteTests/MockStorageValidator.swift
  SimplenoteTests/SharedStorageMigratorTests.swift
Labels: [feature] shortcuts

#1163 Shortcuts: Open Note
  IntentsExtension/Extensions/FileManager+Intents.swift
  IntentsExtension/Extensions/IntentNote+Helpers.swift
  IntentsExtension/IntentHandler.swift
  IntentsExtension/IntentHandlers/OpenNoteIntentHandler.swift
  IntentsExtension/Models/Note+Intents.swift
  IntentsExtension/Models/SPManagedObject+Intents.swift
  IntentsExtension/Support Files/Info.plist
  IntentsExtension/Support Files/IntentsExtension.entitlements
  IntentsExtension/Support Files/IntentsExtensionDebug.entitlements
  IntentsExtension/Tools/ExtensionCoreDataWrapper.swift
  IntentsExtension/Tools/ExtensionResultsController.swift
  IntentsExtension/Tools/IntentsConstants.swift
  IntentsExtension/Tools/IntentsError.swift
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/ActivityType.swift
  Simplenote/Bundle+Simplenote.swift
  Simplenote/CoreDataManager.swift
  Simplenote/NSUserInterfaceItemIdentifier+Simplenote.swift
  Simplenote/ShortcutIntents.intentdefinition
  Simplenote/Simplenote-Info.plist
  Simplenote/SimplenoteAppDelegate+Swift.swift
  Simplenote/SortMode.swift
  Simplenote/String+Simplenote.swift
Labels: [feature] shortcuts

#1165 Shortcut: Find Note With Content Intent
  IntentsExtension/Extensions/IntentNote+Helpers.swift
  IntentsExtension/IntentHandler.swift
  IntentsExtension/IntentHandlers/FindNoteIntentHandler.swift
  IntentsExtension/Support Files/Info.plist
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/ShortcutIntents.intentdefinition
  Simplenote/Simplenote-Info.plist
Labels: [feature] shortcuts
